### ISSUE TITLE
Nested Types not decoded

### ISSUE THREAD

**Issue by ibengeu** [Swiftgram/TDLibKit#24]
How does the encoding/decoding work?. Currently experiencing this issue where nested types are not decoded or encoded.  ie. getting nil as a value @Kylmakalle 

<img width="673" alt="Screenshot 2023-01-10 at 9 56 34 PM" src="https://user-images.githubusercontent.com/29308100/211660870-bb67e935-2c2d-46ca-beb1-ad91446aaf2b.png">

**Comment by Kylmakalle** [comment]
Hello. Nested types are decoded, otherwise you won't have any content in messages.

Talking about `updateNewChat`, I see a small comment about this method in official tdlib docs https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1update_new_chat.html

> A new chat has been loaded/created. This update is guaranteed to come before the chat identifier is returned to the application. The chat field changes will be reported through separate updates.

It seems like at some cases this method may not be fulfilled with data when chat is in creation process. I suggest you to take a look at further updates from server to get full info.
