### ISSUE TITLE
SWIFT TASK CONTINUATION MISUSE: execute(query:) leaked its continuation!

### ISSUE THREAD

**Issue by ggoraa** [Swiftgram/TDLibKit#3]
This is the message I get when I try to execute a normal function in TDLibKit, such as `setAuthenticationPhoneNumber(phoneNumber:settings:)`. Invocation:
```swift
TextField("Phone number", text: $phoneNumber)
  .onSubmit {
      Task {
          try await tdApi.setAuthenticationPhoneNumber(phoneNumber: phoneNumber, settings: nil)
      }
  }
```
Where did I screw up?

**Comment by Kylmakalle** [comment]
Hey, I've been unable to run your app from https://github.com/ggoraa/moc due to missing files in git and reproduce the issue in [unit tests](https://github.com/Swiftgram/TDLibKit/blob/main/Tests/Shared/Tests.swift#L99-L112) even.


I think this is due to ARC `weak self` was used for async function `execute(query:)`.
https://github.com/Swiftgram/TDLibKit/commit/e39cf70f69c12362e860794ef94a10eafe15d6be#diff-0c4989f772de41032c2478b21eb80fc2c46d6f924f6920fda58ee15f574d92a9L13085

@ggoraa Can you please try with latest TDLibKit version 1.2.0?

**Comment by ggoraa** [comment]
Lemme try it, thanks!

**Comment by ggoraa** [comment]
And what do you mean "missing files"? Which exactly?

**Comment by Kylmakalle** [comment]
Clone the repo to clean directory and try to build it. Compiler will throw an error about missing source files.

**Comment by ggoraa** [comment]
>  think this is due to ARC weak self was used for async function execute(query:) which was removed
Well, possibly not this was the issue, because the app still fails to execute this statement with the error above

**Comment by ggoraa** [comment]
`Clone the repo to clean directory and try to build it. Compiler will throw an error about missing source files.`

Sorry, this is an issue in `master` branch. Can you try the `viewmodels+di` one?

**Comment by Kylmakalle** [comment]
I've debugged your app a bit and found out that client is not created on this stage of user flow. It's not nicely handled by framework so you're getting such errors.

The real error is that td client instance is not created. It may be caused by your DI library.
![image](https://user-images.githubusercontent.com/24507532/147892775-7e5ba972-8370-466e-ae12-bfde6e08a454.png)


P.S. Thank you for submitting this issue, I will fix error handling soon.

**Comment by ggoraa** [comment]
Oh, well that is awkward
I have no idea why my DI library refuses to properly init TDLib 🤔
Anyways, thanks for help! Gonna try fixing the issue, or just replace Resolver with Swinject

**Comment by ggoraa** [comment]
Did some more research of this problem. The thing is - the client is still destroyed, even when I use a totally new instance of TDLib (`TdApi(client: TdClientImpl())`)
It is possible that the issue is not my DI library
But the most confusing part is that this thing works fine in TdService, it easily gets the TdApi instance from Resolver and runs functions, such as setTdlibParameters
But it is still broken in LoginView 🤔 
well this is confusing

**Comment by ggoraa** [comment]
I found even more info
When I place in `.onAppear` `tdApi.client.run { _ in }`, and then i run `setAuthenticationPhoneNumber`, the app just dies with the following error:

`_Concurrency/CheckedContinuation.swift:164: Fatal error: SWIFT TASK CONTINUATION MISUSE: execute(query:) tried to resume its continuation more than once, returning Ok()!`
![image](https://user-images.githubusercontent.com/61655029/147924092-3756e846-4619-432a-8f31-093105deaf2c.png)

**Comment by ggoraa** [comment]
Again, more info
If I run the initialization right inside the LoginView, everything works like a charm. I even managed to log in to Telegram!
This is definitely an issue with the DI library...
this is embarassin'...

**Comment by Kylmakalle** [comment]
> It is possible that the issue is not my DI library

It looks like your DI library somehow copies initial `TdApi` object and resets it's state.

**Comment by ggoraa** [comment]
Big thanks for help! And sorry for bothering you because of issues that i created on my end :(

**Comment by Kylmakalle** [comment]
>`_Concurrency/CheckedContinuation.swift:164: Fatal error: SWIFT TASK CONTINUATION MISUSE: execute(query:) tried to resume its continuation more than once, returning Ok()!`

I've also encountered this bug. Fun fact, it was due to `Error()` can be successfully cast to `Ok()` type.
It's now handled in latest TDLibKit `1.2.1` with some more error-handling logic that could help debugging later.
https://github.com/Swiftgram/TDLibKit/commit/d8deb5e1cb0793401c065aad71ddba8e29fffb16
