### ISSUE TITLE
TestFlight upload failed - CFBundleShortVersionString

### ISSUE THREAD

**Issue by marcotammaro** [Swiftgram/TDLibKit#51]
Hello, thank you for the amazing works you are doing with TDLibKit.
I'm currently trying to implement TDLibKit in a sample app but when I try to upload a version to TestFlight (Xcode -> Product -> Archive -> Upload) I got an error related to an incompatible format of CFBundleShortVersionString.

The complete error is:
```
Asset validation failed
This bundle is invalid. The value for key CFBundleShortVersionString *1.8.28-2424d681' in the
Info.plist file at "Payload/AppName.app/Frameworks/
TDLibFramework.framework' must be a period-separated list of at most three non-negative
integers. Please find more information about CFBundleShortVersionString at https://
developer.apple.com/documentation/bundleresources/information_property_list/
cfbundleshortversionstring
```

Any help would be really appreciated 😁

Kind Regards,
Marco

**Comment by Kylmakalle** [comment]
Underlying issue
https://github.com/Swiftgram/TDLibFramework/issues/258

**Comment by Kylmakalle** [comment]
TDLibFramework consumed and the issue have been fixed in https://github.com/Swiftgram/TDLibKit/releases/tag/1.5.2-tdlib-1.8.29-39d82693

@marcotammaro Please check and let me know if anything else is wrong. Would be happy to connect in Telegram [@Kylmakalle](https://t.me/Kylmakalle) to know more about your project.
